### 챌린지 생성 API (CREATE)
# Requires accessToken in http-client.private.env.json
POST {{baseUrl}}/api/challenge/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "파이썬 중급",
    "source": "https://docs.python.org/3/tutorial/index.html",
    "field": "API",
    "type": "OFFICIAL",
    "deadline": "2025-12-05T23:59:59+09:00",
    "capacity": "2",
    "content": "파이썬은 고급 범용 프로그래밍 언어입니다."
}

### 챌린지 수정 API (UPDATE)
PATCH {{baseUrl}}/api/challenge/update/2f23367e-027e-4544-ab18-adde5f523ec5
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "title": "파이썬 고급",
  "content": "파이썬은 매우 강력한 프로그래밍 언어입니다.",
  "type": "OFFICIAL"
}

### 챌린지 취소 API (CANCEL)
PATCH {{baseUrl}}/api/challenge/cancel/2f23367e-027e-4544-ab18-adde5f523ec5
Authorization: Bearer {{accessToken}}
content-type: application/json

{}

### 챌린지 삭제 API (DELETE)
PATCH {{baseUrl}}/api/challenge/delete/2f23367e-027e-4544-ab18-adde5f523ec5
Authorization: Bearer {{accessToken}}
content-type: application/json

{}

### 챌린지 완전 삭제 API (HARD DELETE)
DELETE {{baseUrl}}/api/challenge/hard-delete/2f23367e-027e-4544-ab18-adde5f523ec5
Authorization: Bearer {{accessToken}}
content-type: application/json

{}