### GET Work List
GET {{baseUrl}}/api/challenge/work/translated-list?challengeId=0685b51d-953f-4943-bef7-8eebba911e8e&page=1&size=10
Authorization: Bearer {{accessToken}}

### GET Work Detail
GET {{baseUrl}}/api/challenge/work/translated-detail/dda81aff-0289-4d6d-996b-b1c9863e86a3
Authorization: Bearer {{accessToken}}

### GET Save List
GET {{baseUrl}}/api/challenge/work/translated-list/save?challengeId=0685b51d-953f-4943-bef7-8eebba911e8e&page=1&size=10
Authorization: Bearer {{accessToken}}

### GET Save Detail
GET {{baseUrl}}/api/challenge/work/translated-detail/save/dda81aff-0289-4d6d-996b-b1c9863e86a3
Authorization: Bearer {{accessToken}}

### POST Create Work
POST {{baseUrl}}/api/challenge/work/translated-detail
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "challengeId": "e5b29ba5-6f0a-4735-af1a-6c84b678cd1c",
  "title": "작업물 제목",
  "workItem": "번역 내용"
}

### POST Create Save Work
POST {{baseUrl}}/api/challenge/work/translated-detail/save
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "challengeId": "0685b51d-953f-4943-bef7-8eebba911e8e",
  "title": "임시 저장 제목",
  "workItem": "임시 저장 내용"
}

### PATCH Update Work
PATCH {{baseUrl}}/api/challenge/work/translated-detail/dda81aff-0289-4d6d-996b-b1c9863e86a3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "수정된 제목",
  "workItem": "수정된 번역 내용"
}

### DELETE Work
DELETE {{baseUrl}}/api/challenge/work/translated-detail/dda81aff-0289-4d6d-996b-b1c9863e86a3
Authorization: Bearer {{accessToken}}

### POST Toggle Like
POST {{baseUrl}}/api/challenge/work/translated-detail/like/dda81aff-0289-4d6d-996b-b1c9863e86a3
Authorization: Bearer {{accessToken}}
