### GET request to example server

POST http://localhost:3000/api/auth/login
content-type: application/json

//{
//  "email": "admin2@example.com",
//  "password": "admin2"
//}

{
  "email": "admin@example.com",
  "password": "pw1000"
}

### GET request to example server

POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "email": "user2@example.com",
  "password": "pw1001"
}
