### Admin 챌린지 조회 API

GET http://localhost:3000/api/challenge/admin/inquiry/challenge-list?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMGMyMzVkMi1jOTdmLTQxYjItYjM2Zi00ZmFmOGMxMzI0M2YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjE3MDA0MDYsImV4cCI6MTc2MTc4NjgwNn0.0isiZw8ZdCvY_X4-fkEG_Y9FOYY3AUOEUbDAvsAHgvY

### Admin 챌린지 상세 조회 API

GET http://localhost:3000/api/challenge/admin/inquiry/challenge/0685b51d-953f-4943-bef7-8eebba911e8e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMGMyMzVkMi1jOTdmLTQxYjItYjM2Zi00ZmFmOGMxMzI0M2YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjE3MDA0MDYsImV4cCI6MTc2MTc4NjgwNn0.0isiZw8ZdCvY_X4-fkEG_Y9FOYY3AUOEUbDAvsAHgvY

### 챌린지 승인 API

PATCH http://localhost:3000/api/challenge/admin/new-challenge/approve/0685b51d-953f-4943-bef7-8eebba911e8e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMGMyMzVkMi1jOTdmLTQxYjItYjM2Zi00ZmFmOGMxMzI0M2YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjE3MDA0MDYsImV4cCI6MTc2MTc4NjgwNn0.0isiZw8ZdCvY_X4-fkEG_Y9FOYY3AUOEUbDAvsAHgvY
content-type: application/json

{}

### 챌린지 거절 API

PATCH http://localhost:3000/api/challenge/admin/new-challenge/reject/0685b51d-953f-4943-bef7-8eebba911e8e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMGMyMzVkMi1jOTdmLTQxYjItYjM2Zi00ZmFmOGMxMzI0M2YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjE3MDA0MDYsImV4cCI6MTc2MTc4NjgwNn0.0isiZw8ZdCvY_X4-fkEG_Y9FOYY3AUOEUbDAvsAHgvY
content-type: application/json

{
  "reject_comment": "챌린지 내용이 부적절합니다."
}